name: Remove Unused Code

on:
  push:
    branches: [ main ]

jobs:
  remove-unused-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install coverage coverage-toc coverage-badge
    - name: Run tests and generate coverage report
      run: |
        coverage run -m unittest discover
        coverage report
        coverage html
        coverage xml
        coverage_toc --output "coverage.md"
        coverage-badge -f -o coverage.svg
      env:
        CI: true
    - name: Remove unused code
      if: ${{ github.event_name == 'push' && success() }}
      run: |
        coverage erase
        readarray -t files < <(git ls-files -m | grep .py)
        for file in "${files[@]}"
        do
          echo "Removing unused code in $file"
          coverage run $file > /dev/null
          coverage report $file | grep -v "^TOTAL$" | awk '{ print $2 }' | xargs sed -i '/^$/d'
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}