name: Remove Unused Code

on:
  push:
    branches: [ main ]

jobs:
  remove-unused-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install flake8 flake8-unused-code
    - name: Check for unused code
      run: |
        flake8 --select F401 --ignore E402,W503 .
      continue-on-error: true
    - name: Remove unused code
      if: ${{ github.event_name == 'push' && success() }}
      run: |
        flake8 --select F401 --ignore E402,W503 --per-file-ignores --extend-ignore=F .
        readarray -t files < <(git ls-files -m | grep .py)
        for file in "${files[@]}"
        do
          echo "Removing unused code in $file"
          sed -i -e "$(flake8 --select F401 --ignore E402,W503 --per-file-ignores --extend-ignore=F $file | sed 's/:.*//g' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/,/g')d" $file
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
